// Generated by CoffeeScript 1.3.3
(function() {
  var http, port, x, y;

  http = require('http');

  port = 1337;

  x = 250;

  y = 250;

  http.createServer(function(req, res) {
    var value;
    value = "";
    if (req.url !== "/favicon.ico") {
      value = req.url.slice(1);
      switch (value) {
        case "left":
          x -= 10;
          break;
        case "right":
          x += 10;
          break;
        case "up":
          y -= 10;
          break;
        case "down":
          y += 10;
      }
    }
    if (x > 475) {
      x = 475;
      console.log("Right wall collision");
    } else if (x < 25) {
      x = 25;
      console.log("Left wall collision");
    }
    if (y > 475) {
      y = 475;
      console.log("Bottom wall collision");
    } else if (y < 25) {
      y = 25;
      console.log("Top wall collision");
    }
    if (value !== "") {
      console.log(value);
    }
    res.writeHead(200, {
      "content-type": "text/plain"
    });
    return res.end("" + x + "&" + y);
  }).listen(port);

  console.log("Server has begun on port " + port);

}).call(this);
